# Generated by Django 4.0.6 on 2024-07-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True, verbose_name='Name')),
                ('capital', models.CharField(max_length=125, verbose_name='Capital')),
                ('area', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Area, sq.km')),
                ('population', models.PositiveIntegerField(verbose_name='Population')),
            ],
        ),
    ]
